# -*- coding: utf-8 -*-
"""lub 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oMMz1SaEjL9Xtm5pTQAC2ljSoa98Icmv
"""

answer = int(input("Введи число: "))
if answer > 5:
  print("hello world")
elif answer == 6:
  print("Молодец")
else:
  print("Ошибкааааааааааа")

#1
b = int(input("Введи число: "))
a = 5
print(a * b)

#2
a = int(input("Введи первое число: "))
b = int(input("Введи второе число: "))
print((a + b)**2)

#3
a = 15
b = 10
c = int(input("Введи число: "))
print((a + b) / c)

#4
a = int(input("Введи число a: "))
b = int(input("Введи число b: "))
print(a**2 + 2*a*b + b**2)

#5
a = int(input("Введи длину стороны a: "))
b = int(input("Введи длину стороны b: "))
c = int(input("Введи длину стороны c: "))
perimetr = a + b + c
poly_p = perimetr / 2
ploshad = (poly_p*(poly_p - a)*(poly_p - b)*(poly_p - c))**0.5
print("Площадь равна: ", ploshad)
print("Периметр равен: ", perimetr)

#6
a = int(input("Введи число a: "))
b = int(input("Введи число b: "))
print(((a**3 + 14) / 5) * b)

#7
a = int(input("Введи число a: "))
n = int(input("Введи число n: "))
print(a**2 // n)

#8
a = float(input("Введи число a: "))
b = float(input("Введи число b: "))
print(a // b)
print("--------------------")
a1 = int(input("Введи число a1: "))
b1 = int(input("Введи число b1: "))
if a1 > 0 and b1 > 0:
  print(a1 * b1)
else:
  print("Загугли натуральные числа, а потом приходи")
print("--------------------")
a2 = int(input("Введи число a2: "))
b2 = int(input("Введи число b2: "))
if a2 > 0 and b2 > 0:
  print(a2 % b2)
else:
  print("")

#last task(рабочи код)
n = int(input("Введи число: "))
sec_in_day = 3600 * 24
dni = n // (3600 * 24)
hours = n % sec_in_day // 3600
min = n % sec_in_day % 3600 // 60
#sec = n % sec_in_day % 3600 % 60
print(dni,":",hours,":",min)

#last task(рабочий, но смешной код)
n = int(input("Введи число: "))
dni = n // (3600 * 24)
hours = (n - (dni * 3600 * 24)) // 3600
if hours == 0:
  min = (n - (dni * 24 * 3600)) // 60
else:
  min = (n - (dni * 3600 * 24 + hours * 3600)) // 60
print(dni,":",hours,":",min)

n = int(input("Введи секунды: "))  #код, чтобы поржать(нерабочий)
dni = n // (3600 * 24)
hours = (n - (dni * 3600 * 24)) % 3600
min = (n - (hours * 3600)) % 60
sec = n - (min * 60)
print(dni,":",hours,":",min,":",sec)