# -*- coding: utf-8 -*-
"""lub 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pLskuF0q_v6Mt_LGd5TvlauQWgPzGtU0
"""

#1
n = int(input("Введи номер месяца: "))
if n == 1:
  print("Январь")
elif n == 2:
  print("Февраль")
elif n == 3:
  print("Март")
elif n == 4:
  print("Апрель")
elif n == 5:
  print("Май")
elif n == 6:
  print("Июнь")
elif n == 7:
  print("Июль")
elif n == 8:
  print("Август")
elif n == 9:
  print("Сентябрь")
elif n == 10:
  print("Октябрь")
elif n == 11:
  print("Ноябрь")
elif n == 12:
  print("Декабрь")
else:
  print("Самый умный что-ли?")

#2
answer = int(input("Введи число: "))
if answer % 2 == 0:
  print("Число чётное")
else:
  print("Число нечётное")

#3
n = int(input("Введи число "))
if n > 40:
  print("stonks")
elif n < 40:
  print("not stonks")
else:
  print("Словил баланс")

#4
def is_year_leap(year):
  if year % 4 == 0:
    return True
  else:
    return False
answer = int(input("Введи год: "))
is_year_leap(answer)

#5
count = 0
def  is_prime(n):
  global count
  for x in range(1, n + 1):
    if n % x == 0:
      count += 1
  if count > 2:
    return False
  else:
    return True
a = int(input())
is_prime(a)

#6
a = int(input("Введи число: "))
b = int(input("Введи число: "))
a1 = 11
if a / b == 3.6 or (b >= abs((-138/2)**1.3) and b <= abs(((-69/28)**5.1)*4)):
  a, b = b, a
else:
  print("")
print(a)
print(b)

#7
chet = 0
otric = 0
promejutok = 0
list_number = []
for x in range(5):
  a = int(input("Введи число: "))
  if a % 2 == 0:
    chet += 1
  if a < 0:
    otric += 1
  if a >= -256 and a <= 1024:
    promejutok += 1
  list_number.append(a)
uniq_number = list(set(list_number))
if len(uniq_number) < 5:
  print("Не все числа уникальные")
else:
  print("Все числа уникальные")
print("Чётных:", chet, "Отрицательных:", otric, "Входящих в промежуток:", promejutok)

#last task(все работает, внизу числа a b c, с которыми получается четный ответ) (:
a = int(input("Введи число a: "))
b = int(input("Введи число b: "))
c = int(input("Введи число c: "))
if (((a**2 + b**3) / (c + 3)) / 4) % 2 == 0:
  print("Чётное")
else:
  print("Нечётное")
#a b c
#3 7 8
#3 7 19
#3 7 41
#3 15 6
#3 15 44
#3 31 2
#3 31 22
#3 39 3
#3 39 5